[package]
name = "dnf-scaffold-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "dnf_scaffold"

[dependencies]
lazy_static = "1.4.0"
prun-rs = { git = "https://github.com/dboeger1/prun.git" }
